### ISSUE TITLE
Using settings command may still not work as expected

### ISSUE THREAD

**Issue by xayanide** [ZPTXDev/Quaver#1124]
### Describe the bug
Extension of #841 
I will try to make a demo video and elaborate on this further later, but this may be a bug or just a configuration issue on my end.

### Severity

Critical

### Affected branches

- [X] Stable
- [X] Next

### Quaver version

7.0.1
6.10.0-next.1 (#841)

### Steps to reproduce

1. Start Quaver
2. Use settings command

### Expected behavior

Show the settings.

### Actual behavior

Discord shows that `The application did not respond.`

### Relevant log output

```js

2024-04-12T03:54:42.951Z  INFO  Discord Connected. Logged in as Aia#3990.
2024-04-12T03:54:42.952Z  INFO  Quaver Running version 7.0.1. For help, see https://github.com/ZPTXDev/Quaver/issues.
2024-04-12T04:37:24.167Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Processing command play query:https://youtu.be/YwHDMYq0S3g?si=bM_3AxKhE94w5kfr&t=779
2024-04-12T04:37:24.293Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Executing command play query:https://youtu.be/YwHDMYq0S3g?si=bM_3AxKhE94w5kfr&t=779
2024-04-12T04:37:28.733Z  INFO  Quaver [G 906471497231630336] Starting track
2024-04-12T04:37:48.362Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Processing command playing  
2024-04-12T04:37:48.437Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Executing command playing   
2024-04-12T05:01:27.608Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Processing command settings 
2024-04-12T05:01:28.069Z  INFO  Quaver [G 906471497231630336 | U 250934589621665793] Executing command settings  
2024-04-12T05:01:28.751Z  ERROR  Quaver Received one or more errors
Error: Received one or more errors
    at _UnionValidator.handle (D:\Documents\GitHub\Quaver\node_modules\@sapphire\shapeshift\dist\index.js:1125:23)
    at _UnionValidator.parse (D:\Documents\GitHub\Quaver\node_modules\@sapphire\shapeshift\dist\index.js:216:88) 
    at EmbedBuilder.setDescription (D:\Documents\GitHub\Quaver\node_modules\@discordjs\builders\dist\index.js:319:26)
    at buildSettingsPage (file:///D:/Documents/GitHub/Quaver/dist/lib/util/util.js:398:22)
    at async Object.execute (file:///D:/Documents/GitHub/Quaver/dist/commands/settings.js:19:48)
```

**Comment by zapteryx** [comment]
should be fixed by https://github.com/ZPTXDev/Quaver/commit/621e05bfd46390a73273cf97f8284ee847a7013a
