### ISSUE TITLE
Error in console if timed out mid-session

### ISSUE THREAD

**Issue by xayanide** [ZPTXDev/Quaver#384]
**Describe the bug**
What isn't working as intended, and what does it affect?
Condition intermittently working, sometimes not at all.
The error is `DiscordAPIError[50013]: Missing Permissions`
I would like a more consistent solution.

Extension of issue #222

**Severity**
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
`> 3.4.0`

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Play any track with Quaver in a voice or stage channel
2. Manually time out Quaver

**Expected behavior**
What is expected to happen?
Show no error at all.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
https://github.com/ZPTXDev/Quaver/blob/c1cd9d8682907f2a00364b5fec822448260a6b55/classes/PlayerHandler.js#L80
^ Sometimes this condition becomes false and the message gets sent to the channel while Quaver is timed out (which Quaver cannot).
We need a more consistent solution.

```js
$ node .
2022-07-18T08:36:42.713Z [Discord] INFO: Connected. Logged in as Aia#3990.
2022-07-18T08:36:42.719Z [Quaver] INFO: Running version 5.0.0-next.2. For help, see https://github.com/ZPTXDev/Quaver/issues.
2022-07-18T08:36:42.720Z [Quaver] WARN: You are running an unstable version of Quaver. Please report bugs using the link above, and note that f
eatures may change or be removed entirely prior to release.
2022-07-18T08:36:46.161Z [Lavalink] INFO: Connected.
2022-07-18T08:37:47.273Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command play
2022-07-18T08:37:47.276Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command play
2022-07-18T08:37:51.316Z [Quaver] INFO: [G 906471497231630336] Starting track
2022-07-18T08:38:27.005Z [Quaver] INFO: [G 906471497231630336] Cleaning up
2022-07-18T08:38:35.607Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command play
2022-07-18T08:38:35.610Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command play
2022-07-18T08:38:56.378Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command play
2022-07-18T08:38:56.379Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command play
2022-07-18T08:39:01.528Z [Quaver] INFO: [G 906471497231630336] Starting track
2022-07-18T08:39:15.894Z [Quaver] INFO: [G 906471497231630336] Cleaning up
2022-07-18T08:39:16.373Z [Quaver] ERROR: Missing Permissions
DiscordAPIError[50013]: Missing Permissions
    at SequentialHandler.runRequest (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:74
8:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\node_modules\@discordjs\rest\dist\ind
ex.js:560:14)
    at async REST.request (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:1000:22)
    at async StageInstanceManager.delete (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\managers\StageInstanceManager.js:150
:5)
    at async StageInstance.delete (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\structures\StageInstance.js:129:5)
    at async PlayerHandler.disconnect (C:\Users\Ava\Documents\GitHub\Quaver\classes\PlayerHandler.js:34:6)
    at async Object.execute (C:\Users\Ava\Documents\GitHub\Quaver\events\voiceStateUpdate.js:31:5)
```

`trackStart.js` might be affected as well.

**Comment by xayanide** [comment]
#379
#357 

And this issue, are indirectly fixed by a change as of Quaver version `7.0.1`, no longer reproducible, will reopen if this occurs again.

**Comment by xayanide** [comment]
After the 50th try, this still occurs, but rarely.

**Comment by zapteryx** [comment]
this is quite an edge case and really depends on what event we get sent first
when timed out, the first thing that tends to happen is disconnection, which typically means the bot leaves the channel and the disconnected message is sent
i've tried this and didn't see any missing permissions message which means that we're most likely not trying to send the message anymore, so i'm not sure if this issue is still persistent
